# Generated by Django 4.2.5 on 2024-07-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_image', models.ImageField(upload_to='category_images/')),
                ('category', models.CharField(default='', max_length=100)),
                ('short_caption', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
