# Generated by Django 4.2.5 on 2024-07-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='gender',
            field=models.ManyToManyField(to='dashboard.gender'),
        ),
    ]
