# Generated by Django 5.0.3 on 2024-07-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes Available',
            },
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Categories', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'Gender', 'verbose_name_plural': 'Gender Category'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider', 'verbose_name_plural': 'Main Slider'},
        ),
        migrations.RemoveField(
            model_name='categories',
            name='gender',
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='', max_length=50, unique=True)),
                ('bulk_upload', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'unique_together': {('keyword',)},
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
