# Generated by Django 5.0.3 on 2024-07-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
    ]
