# Generated by Django 5.0.3 on 2024-07-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_keywords_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.ManyToManyField(to='dashboard.gender'),
        ),
    ]
