# Generated by Django 5.0.3 on 2024-07-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_product_gender_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
