# Generated by Django 5.0.3 on 2024-07-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_categories_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
