# Generated by Django 5.0.3 on 2024-07-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_categories_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
