# Generated by Django 5.0.3 on 2024-07-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stars',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.PositiveIntegerField(default=1200),
        ),
    ]
