# Generated by Django 5.0.3 on 2024-07-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_product_stars_alter_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=models.ImageField(blank=True, null=True, upload_to='size_chart/'),
        ),
    ]
