# Generated by Django 5.0.3 on 2024-07-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_product_size_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='before_discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
    ]
