# Generated by Django 5.0.3 on 2024-07-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_cart_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
