# Generated by Django 5.0.3 on 2024-07-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_cart_ordered_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='caption',
        ),
        migrations.AddField(
            model_name='slider',
            name='short_caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
