# Generated by Django 5.0.3 on 2024-07-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_remove_slider_caption_slider_short_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='redirect_url',
            field=models.CharField(default='#', max_length=500),
        ),
    ]
