# Generated by Django 5.0.3 on 2024-08-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
