# Generated by Django 5.0.3 on 2024-08-24 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_productimage_options_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
    ]
