# Generated by Django 5.0.3 on 2024-08-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='short_caption',
            field=models.CharField(default='', max_length=30),
        ),
    ]
