# Generated by Django 5.0.3 on 2024-08-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_product_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
