# Generated by Django 4.2.7 on 2024-10-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_recentlystalked'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recentlystalked',
            unique_together={('user', 'product')},
        ),
    ]
