# Generated by Django 5.0.3 on 2024-08-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider1_image', models.ImageField(blank=True, null=True, upload_to='slider_images/')),
                ('slider1_caption', models.CharField(blank=True, max_length=255)),
                ('slider1_url', models.URLField(blank=True)),
                ('slider2_image', models.ImageField(blank=True, null=True, upload_to='slider_images/')),
                ('slider2_caption', models.CharField(blank=True, max_length=255)),
                ('slider2_url', models.URLField(blank=True)),
                ('slider3_image', models.ImageField(blank=True, null=True, upload_to='slider_images/')),
                ('slider3_caption', models.CharField(blank=True, max_length=255)),
                ('slider3_url', models.URLField(blank=True)),
                ('site_header_news', models.TextField(blank=True)),
                ('main_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('slider_background_color', models.CharField(blank=True, help_text='Enter color in HEX format, e.g., #FFFFFF', max_length=7)),
            ],
        ),
    ]
