# Generated by Django 5.0.3 on 2024-08-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_sitesettings_site_header_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
