# Generated by Django 5.0.3 on 2024-08-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sitesettings_site_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='slider1_caption',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='slider2_caption',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='slider3_caption',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slider1_caption1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slider1_caption2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slider2_caption1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slider2_caption2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slider3_caption1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slider3_caption2',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
