# Generated by Django 5.0.3 on 2024-08-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_sitesettings_slider1_caption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='main_logo',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
