# Generated by Django 5.0.3 on 2024-08-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_main_logo_sitesettings_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='main_page_video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='slider_images/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='main_page_video_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
