# Generated by Django 5.0.3 on 2024-08-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_sitesettings_facebook_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='font_style',
            field=models.CharField(choices=[('font-sans', 'Sans-serif'), ('font-serif', 'Serif'), ('font-mono', 'Monospace')], default='font-sans', max_length=10),
        ),
    ]
