# Generated by Django 5.0.3 on 2024-09-02 00:50

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_sitesettings_font_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_header_news',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Text'),
        ),
    ]
