# Generated by Django 5.0.3 on 2024-09-03 14:36

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_sitesettings_site_header_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_header_news',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
