# Generated by Django 4.2.7 on 2024-10-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_sitesettings_site_header_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_key_id', models.CharField(default='', max_length=500)),
                ('razorpay_key_secret', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Payment Gateway Setting',
                'verbose_name_plural': 'Payment Gateway',
            },
        ),
    ]
