# Generated by Django 4.2.7 on 2024-10-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_paymentgateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductByCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider_images/')),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Product By Category',
                'verbose_name_plural': 'Product By Category',
            },
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
    ]
